/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import DAO.DAO;
import DAO.DAOfactory;
import DAO.DaoContrat;
import exception.ExceptionMetier1;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import metier.*;
import javax.swing.JComboBox;
import list.*;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author CDA03-16
 */
public class MenuPrincipal1  extends javax.swing.JFrame {
    
    
    
    private String choix;
    private Societe1 sc;
    private int modif=0;
    
    
  

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal1()throws ExceptionMetier1{
        initComponents();
        btnRetourClientsProspect.setVisible(false);
        cbxClientProspect.removeAllItems();
        
        paBtnMenuCreeModifierAfficher.setVisible(false);
        cbxClientProspect.setVisible(false);
        lblChoixduclients.setVisible(false);
        this.setTitle("Reverso");
       // this.setIconImage(new ImageIcon(getClass().getResource("/image/img1.png")).getImage());
        
        
        
        
    }
      public MenuPrincipal1(String p_choix)throws ExceptionMetier1,ParseException{
        initComponents();
            choix=p_choix;
            btnRetourClientsProspect.setVisible(true);
            cbxClientProspect.removeAllItems();
        
        if(p_choix.equalsIgnoreCase("clients")){
            
            
            lblTitre.setText("Gestion des clients");
            paMenuClientsProspects.setVisible(false);     
            paBtnMenuCreeModifierAfficher.setVisible(true);           
            lblChoixduclients.setText("liste des "+p_choix);
            lblChoixduclients.setVisible(true);
            //ajout clients dans la combobox
            for(int i=0;i<ListClient1.getListClients().size();i++){
                getCbxClientProspect().addItem(ListClient1.getListClients().get(i).getRaisonSociale());
            }
            getCbxClientProspect().setVisible(true);
            btnContrat.setVisible(true);

        }
        else{
          
            lblTitre.setText("Gestion des prospects");
            paMenuClientsProspects.setVisible(false);
            paBtnMenuCreeModifierAfficher.setVisible(true);                   
            lblChoixduclients.setText("liste des "+p_choix);
            lblChoixduclients.setVisible(true);
            //ajout prospect dans la combobox
            for(int i=0;i<ListProspect1.getListProspect().size();i++){
                    getCbxClientProspect().addItem(ListProspect1.getListProspect().get(i).getRaisonSociale());
                }
                getCbxClientProspect().setVisible(true);
                btnContrat.setVisible(false);
            
        }
        
    }
    


    public JComboBox<String> getCbxClientProspect(){
        return cbxClientProspect;
    }

    public JLabel getLblChoixduclients() {
        return lblChoixduclients;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paMenuClientsProspects = new javax.swing.JPanel();
        btnClients = new javax.swing.JButton();
        btnProspects = new javax.swing.JButton();
        lblTitre = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JButton();
        paBtnMenuCreeModifierAfficher = new javax.swing.JPanel();
        btnCreer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnAfficher = new javax.swing.JButton();
        btnContrat = new javax.swing.JButton();
        cbxClientProspect = new javax.swing.JComboBox<>();
        btnRetourClientsProspect = new javax.swing.JButton();
        lblChoixduclients = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnClients.setText("Clients");
        btnClients.setFocusPainted(false);
        btnClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientsActionPerformed(evt);
            }
        });

        btnProspects.setText("Prospects");
        btnProspects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProspectsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paMenuClientsProspectsLayout = new javax.swing.GroupLayout(paMenuClientsProspects);
        paMenuClientsProspects.setLayout(paMenuClientsProspectsLayout);
        paMenuClientsProspectsLayout.setHorizontalGroup(
            paMenuClientsProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paMenuClientsProspectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btnProspects)
                .addContainerGap())
        );
        paMenuClientsProspectsLayout.setVerticalGroup(
            paMenuClientsProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paMenuClientsProspectsLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(paMenuClientsProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProspects))
                .addGap(37, 37, 37))
        );

        lblTitre.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("\tGestion des Clients-Prospects");
        lblTitre.setAlignmentX(50.0F);

        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        btnCreer.setText("cree");
        btnCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerActionPerformed(evt);
            }
        });

        btnModifier.setText("modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnAfficher.setText("afficher");
        btnAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherActionPerformed(evt);
            }
        });

        btnContrat.setText("Contrats");
        btnContrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paBtnMenuCreeModifierAfficherLayout = new javax.swing.GroupLayout(paBtnMenuCreeModifierAfficher);
        paBtnMenuCreeModifierAfficher.setLayout(paBtnMenuCreeModifierAfficherLayout);
        paBtnMenuCreeModifierAfficherLayout.setHorizontalGroup(
            paBtnMenuCreeModifierAfficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paBtnMenuCreeModifierAfficherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreer)
                .addGap(36, 36, 36)
                .addComponent(btnModifier)
                .addGap(41, 41, 41)
                .addComponent(btnSupprimer)
                .addGap(28, 28, 28)
                .addComponent(btnAfficher)
                .addGap(18, 18, 18)
                .addComponent(btnContrat)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        paBtnMenuCreeModifierAfficherLayout.setVerticalGroup(
            paBtnMenuCreeModifierAfficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paBtnMenuCreeModifierAfficherLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(paBtnMenuCreeModifierAfficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreer)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer)
                    .addComponent(btnAfficher)
                    .addComponent(btnContrat))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        cbxClientProspect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRetourClientsProspect.setText("Retour");
        btnRetourClientsProspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourClientsProspectActionPerformed(evt);
            }
        });

        lblChoixduclients.setText("ListeClients");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(paMenuClientsProspects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paBtnMenuCreeModifierAfficher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxClientProspect, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChoixduclients, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 446, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRetourClientsProspect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQuitter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paMenuClientsProspects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paBtnMenuCreeModifierAfficher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblChoixduclients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxClientProspect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRetourClientsProspect)
                .addGap(26, 26, 26)
                .addComponent(btnQuitter)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientsActionPerformed
        
        // TODO add your handling code here:
        lblTitre.setText("Gestion des clients");
        paMenuClientsProspects.setVisible(false);
        paBtnMenuCreeModifierAfficher.setVisible(true);
        btnRetourClientsProspect.setVisible(true);
        for(int i=0;i<ListClient1.getListClients().size();i++){
          
                getCbxClientProspect().addItem(ListClient1.getListClients().get(i).getRaisonSociale());
            
            
        }
      
        
        btnContrat.setVisible(true);
        cbxClientProspect.setVisible(true);
        choix=btnClients.getText();
        lblChoixduclients.setVisible(true);
        lblChoixduclients.setText("liste des "+choix);
        
    }//GEN-LAST:event_btnClientsActionPerformed

    private void btnProspectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProspectsActionPerformed
        // TODO add your handling code here:
        lblTitre.setText("Gestion des prospects");
        paMenuClientsProspects.setVisible(false);
        paBtnMenuCreeModifierAfficher.setVisible(true);
        btnContrat.setVisible(false);
        btnRetourClientsProspect.setVisible(true);
        for(int i=0;i<ListProspect1.getListProspect().size();i++){
        getCbxClientProspect().addItem(ListProspect1.getListProspect().get(i).getRaisonSociale());
        }
        cbxClientProspect.setVisible(true);
        choix=btnProspects.getText();
        lblChoixduclients.setVisible(true);
        lblChoixduclients.setText("liste des "+choix);
    }//GEN-LAST:event_btnProspectsActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        // TODO add your handling code here:
        int reponse =JOptionPane.showConfirmDialog(null,"voulez vous quitter la fenetre","Quitter",JOptionPane.YES_NO_OPTION);
        if(reponse==JOptionPane.YES_OPTION){
            dispose();
            System.exit(0);
        }
                    
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnRetourClientsProspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourClientsProspectActionPerformed
        // TODO add your handling code here:
         lblTitre.setText("Gestion des Clients-Prospects");
         btnRetourClientsProspect.setVisible(false);
         paBtnMenuCreeModifierAfficher.setVisible(false);
         cbxClientProspect.setVisible(false);
         paMenuClientsProspects.setVisible(true);
         cbxClientProspect.removeAllItems();
         lblChoixduclients.setVisible(false);

        
    }//GEN-LAST:event_btnRetourClientsProspectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reponse =JOptionPane.showConfirmDialog(null,"voulez vous quitter la fenetre","Quitter",JOptionPane.YES_NO_OPTION);
                if(reponse==JOptionPane.YES_OPTION){
                    dispose();
                    System.exit(0);
                }
        
    }//GEN-LAST:event_formWindowClosing

    private void btnCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        Formulaires1 cl;
        try {
            cl = new Formulaires1(choix);
            cl.setVisible(true);
            
        } catch (ExceptionMetier1 | ParseException ex) {
            Logger.getLogger(MenuPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_btnCreerActionPerformed

    private void btnAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherActionPerformed
        // TODO add your handling code here:                
        this.setVisible(false);
        
        AffichageClientsProspects1 table=new AffichageClientsProspects1(choix,sc);        
        table.setVisible(true);
                      
    }//GEN-LAST:event_btnAfficherActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        this.modif=1;
        this.setVisible(false);
        if(choix.equalsIgnoreCase("clients")){
             sc =ListClient1.getListClients().get(cbxClientProspect.getSelectedIndex());
        }
        else{
            sc=ListProspect1.getListProspect().get(cbxClientProspect.getSelectedIndex());
            
        }
        Formulaires1 cl;
        try {
            cl = new Formulaires1(choix,modif,sc);
            cl.setVisible(true);
            
        } catch (ExceptionMetier1 | ParseException ex) {
            Logger.getLogger(MenuPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        this.modif=2;   
        this.setVisible(false);
        if(choix.equalsIgnoreCase("clients")){
             sc =ListClient1.getListClients().get(cbxClientProspect.getSelectedIndex());
        }
        else{
            sc=ListProspect1.getListProspect().get(cbxClientProspect.getSelectedIndex());
            
        }
          Formulaires1 cl;
        try {
            cl = new Formulaires1(choix,modif,sc);
            cl.setVisible(true);
          
                        
        } catch (ExceptionMetier1 | ParseException ex) {
            Logger.getLogger(MenuPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnContratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratActionPerformed
        try {                                           
            // TODO add your handling code here:
            this.setVisible(false);
            
            
            sc = ListClient1.getListClients().get(cbxClientProspect.getSelectedIndex());
            
            AffichageClientsProspects1 table=null;
            
            try {
                table = new AffichageClientsProspects1(sc);
            } catch (ExceptionMetier1 | ParseException ex) {
                Logger.getLogger(MenuPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
            }
            table.setVisible(true);
            
            
            
        } catch (SQLException | IOException ex) {
            Logger.getLogger(MenuPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnContratActionPerformed
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MenuPrincipal1().setVisible(true);
            } catch (ExceptionMetier1 ex) {
                Logger.getLogger(MenuPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfficher;
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnContrat;
    private javax.swing.JButton btnCreer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnProspects;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnRetourClientsProspect;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox<String> cbxClientProspect;
    private javax.swing.JLabel lblChoixduclients;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JPanel paBtnMenuCreeModifierAfficher;
    private javax.swing.JPanel paMenuClientsProspects;
    // End of variables declaration//GEN-END:variables
}
